### ISSUE TITLE
项目安装后报错没安装 font-awesome.css

### ISSUE THREAD

**Issue by wploey** [JerryYuanJ/a-vue-app-template#1]
```
This dependency was not found:

* font-awesome/css/font-awesome.css in ./src/main.js

To install it, you can run: npm install --save font-awesome/css/font-awesome.css
```
`package.json` 加入了 `"font-awesome": "^4.7.0"` 在 `main.js` 文件中引用不了, 实在不知道怎么解决..

**Comment by JerryYuanJ** [comment]
还有这个问题吗？是node版本问题吗？我这边跑是没有问题的啊。我这几天有时间重新check一下项目试试吧。你可以先使用cdn的，参考地址：http://www.bootcdn.cn/font-awesome/。

**Comment by mengfanxin** [comment]
我也出这个问题了，找不到这个字体

**Comment by mengfanxin** [comment]
这个字体包已经npm 安装过了。
然后执行run dev 出现下面错误：
 ERROR  Failed to compile with 1 errors                                                                    09:15:46

This dependency was not found:

* font-awesome/css/font-awesome.css in ./src/main.js

To install it, you can run: npm install --save font-awesome/css/font-awesome.css

**Comment by mengfanxin** [comment]
D:\a-vue-app-template-master>npm install --save font-awesome/css/font-awesome.css
npm ERR! code ENOLOCAL
npm ERR! Could not install from "font-awesome\css\font-awesome.css" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-06-12T01_19_00_087Z-debug.log

**Comment by JerryYuanJ** [comment]
issue fixed，sorry for the delay ~
