### ISSUE TITLE
打包发布后，在服务器上渲染效果有问题，紧急求助！！！

### ISSUE THREAD

**Issue by 314086511hello** [JerryYuanJ/a-vue-app-template#2]
怀疑是不是因为mintui没有打包进去吗？
<img width="374" alt="2018-05-31 10 24 34" src="https://user-images.githubusercontent.com/7752312/40757984-a86b8046-64bd-11e8-8c55-1031e18ab2a4.png">
<img width="373" alt="2018-05-31 10 24 08" src="https://user-images.githubusercontent.com/7752312/40757988-acd3afe6-64bd-11e8-9597-55745d5f85b3.png">
<img width="375" alt="2018-05-31 10 24 15" src="https://user-images.githubusercontent.com/7752312/40757992-ae7bd792-64bd-11e8-9d9f-0702deca2f96.png">
<img width="371" alt="2018-05-31 10 24 24" src="https://user-images.githubusercontent.com/7752312/40757995-b0681390-64bd-11e8-9d9a-e2157b87e70c.png">

**Comment by JerryYuanJ** [comment]
你这个肯定是mint-ui的样式没有打包进去啊，可以直接运行一下打包后的index.html然后看看控制台的日志。
