### ISSUE TITLE
大哥，帮忙啊，真心想研究这个项目啊

### ISSUE THREAD

**Issue by mengfanxin** [JerryYuanJ/a-vue-app-template#3]
我把nodejs重装成最新版了，把之前下载的所有npm包和遗留的东西全删了。

最后还是font-awesome这个图标库没有，导致程序跑不起来啊

 ERROR  Failed to compile with 1 errors                                                                    10:26:41

This dependency was not found:

* font-awesome/css/font-awesome.css in ./src/main.js

To install it, you can run: npm install --save font-awesome/css/font-awesome.css

------------------------------------------------------------------

而且npm install 也安装不成功

**Comment by JerryYuanJ** [comment]
OK ，最近有些事一直没看git，我会尽快解决，抱歉～

**Comment by JerryYuanJ** [comment]
issue fixed～sorry for the delay
