### ISSUE TITLE
运行你的demo发现好多错误

### ISSUE THREAD

**Issue by zhangaofei** [JerryYuanJ/a-vue-app-template#7]
你好，运行你的demo发现好多错误如：
 @ ./node_modules/vue-style-loader!./node_modules/css-loader?{"minimize":false,"sourceMap":false}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-4c9afdd1","scoped":true,"hasInlineConfig":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/components/coms/select-header.vue 4:14-413 13:3-17:5 14:22-421
 @ ./src/components/coms/select-header.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/pages/tool/CalendarTest.vue
 @ ./src/pages/tool/CalendarTest.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8899 webpack/hot/dev-server ./src/main.js

 error  in ./src/components/coms/pull-to-refresh.vue
应该是那个地方配置出错了；还有PhantomJS not found on PATH  package.json没有单独的这个文件

**Comment by JerryYuanJ** [comment]
抱歉，无法重现。你试试删掉对应的依赖试试吧。
